### ISSUE TITLE
error on Sponge after creating Nether

### ISSUE THREAD

**Issue by mkrtes** [LexManos/YUNoMakeGoodMap#36]
[14:40:49] [Server thread/INFO] [STDERR]: [net.minecraftforge.lex.yunomakegoodmap.StructureUtil:loadTemplate:52]: java.io.FileNotFoundException: /home/fdw/home/AquaFactory-25885/config/YUNoMakeGoodMap/structures/_nether.nbt
[14:40:49] [Server thread/INFO] [STDERR]: [net.minecraftforge.lex.yunomakegoodmap.StructureUtil:loadTemplate:52]:       at net.minecraftforge.lex.yunomakegoodmap.StructureUtil.loadTemplate(StructureUtil.java:52)
[14:40:49] [Server thread/INFO] [STDERR]: [net.minecraftforge.lex.yunomakegoodmap.StructureUtil:loadTemplate:52]:       at net.minecraftforge.lex.yunomakegoodmap.generators.StructureLoader.generate(StructureLoader.java:34)
[14:40:49] [Server thread/INFO] [STDERR]: [net.minecraftforge.lex.yunomakegoodmap.StructureUtil:loadTemplate:52]:       at net.minecraftforge.lex.yunomakegoodmap.WorldProviderHellVoid$ChunkProviderHellVoid.func_185931_b(WorldProviderHellVoid.java:52)
[14:40:49] [Server thread/INFO] [STDERR]: [net.minecraftforge.lex.yunomakegoodmap.StructureUtil:loadTemplate:52]:       at org.spongepowered.mod.world.gen.SpongeChunkGeneratorForge.func_185931_b(SpongeChunkGeneratorForge.java:246)
[14:40:49] [Server thread/INFO] [STDERR]: [net.minecraftforge.lex.yunomakegoodmap.StructureUtil:loadTemplate:52]:       at net.minecraft.world.chunk.Chunk.func_186034_a(Chunk.java:1000)
[14:40:49] [Server thread/INFO] [STDERR]: [net.minecraftforge.lex.yunomakegoodmap.StructureUtil:loadTemplate:52]:       at net.minecraft.world.chunk.Chunk.func_186030_a(Chunk.java:983)
[14:40:49] [Server thread/INFO] [STDERR]: [net.minecraftforge.lex.yunomakegoodmap.StructureUtil:loadTemplate:52]:       at net.minecraft.world.gen.ChunkProviderServer.func_186025_d(ChunkProviderServer.java:154)
[14:40:49] [Server thread/INFO] [STDERR]: [net.minecraftforge.lex.yunomakegoodmap.StructureUtil:loadTemplate:52]:       at net.minecraft.world.World.func_72964_e(World.java:303)
[14:40:49] [Server thread/INFO] [STDERR]: [net.minecraftforge.lex.yunomakegoodmap.StructureUtil:loadTemplate:52]:       at net.minecraft.world.World.func_175726_f(World.java:298)
[14:40:49] [Server thread/INFO] [STDERR]: [net.minecraftforge.lex.yunomakegoodmap.StructureUtil:loadTemplate:52]:       at net.minecraft.world.World.func_180495_p(World.java:7003)
[14:40:49] [Server thread/INFO] [STDERR]: [net.minecraftforge.lex.yunomakegoodmap.StructureUtil:loadTemplate:52]:       at net.minecraft.world.Teleporter.findPortal(SourceFile:706)
[14:40:49] [Server thread/INFO] [STDERR]: [net.minecraftforge.lex.yunomakegoodmap.StructureUtil:loadTemplate:52]:       at net.minecraft.world.Teleporter.func_180620_b(SourceFile:669)
[14:40:49] [Server thread/INFO] [STDERR]: [net.minecraftforge.lex.yunomakegoodmap.StructureUtil:loadTemplate:52]:       at net.minecraft.world.Teleporter.func_180266_a(SourceFile:608)
[14:40:49] [Server thread/INFO] [STDERR]: [net.minecraftforge.lex.yunomakegoodmap.StructureUtil:loadTemplate:52]:       at org.spongepowered.common.entity.EntityUtil.handleDisplaceEntityPortalEvent(EntityUtil.java:417)
[14:40:49] [Server thread/INFO] [STDERR]: [net.minecraftforge.lex.yunomakegoodmap.StructureUtil:loadTemplate:52]:       at net.minecraft.server.management.PlayerList.transferPlayerToDimension(PlayerList.java:1822)
[14:40:49] [Server thread/INFO] [STDERR]: [net.minecraftforge.lex.yunomakegoodmap.StructureUtil:loadTemplate:52]:       at org.spongepowered.common.entity.EntityUtil.teleportPlayerToDimension(EntityUtil.java:250)
[14:40:49] [Server thread/INFO] [STDERR]: [net.minecraftforge.lex.yunomakegoodmap.StructureUtil:loadTemplate:52]:       at net.minecraft.entity.player.EntityPlayerMP.func_184204_a(EntityPlayerMP.java:4146)
[14:40:49] [Server thread/INFO] [STDERR]: [net.minecraftforge.lex.yunomakegoodmap.StructureUtil:loadTemplate:52]:       at net.minecraft.entity.Entity.func_70030_z(Entity.java:412)
[14:40:49] [Server thread/INFO] [STDERR]: [net.minecraftforge.lex.yunomakegoodmap.StructureUtil:loadTemplate:52]:       at net.minecraft.entity.EntityLivingBase.func_70030_z(EntityLivingBase.java:216)
[14:40:49] [Server thread/INFO] [STDERR]: [net.minecraftforge.lex.yunomakegoodmap.StructureUtil:loadTemplate:52]:       at net.minecraft.entity.Entity.func_70071_h_(Entity.java:359)
[14:40:49] [Server thread/INFO] [STDERR]: [net.minecraftforge.lex.yunomakegoodmap.StructureUtil:loadTemplate:52]:       at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:1932)
[14:40:49] [Server thread/INFO] [STDERR]: [net.minecraftforge.lex.yunomakegoodmap.StructureUtil:loadTemplate:52]:       at net.minecraft.entity.player.EntityPlayer.func_70071_h_(EntityPlayer.java:233)
[14:40:49] [Server thread/INFO] [STDERR]: [net.minecraftforge.lex.yunomakegoodmap.StructureUtil:loadTemplate:52]:       at net.minecraft.entity.player.EntityPlayerMP.func_71127_g(EntityPlayerMP.java:303)
[14:40:49] [Server thread/INFO] [STDERR]: [net.minecraftforge.lex.yunomakegoodmap.StructureUtil:loadTemplate:52]:       at net.minecraft.network.NetHandlerPlayServer.redirect$onPlayerTick$zhb000(NetHandlerPlayServer.java:1968)
[14:40:49] [Server thread/INFO] [STDERR]: [net.minecraftforge.lex.yunomakegoodmap.StructureUtil:loadTemplate:52]:       at net.minecraft.network.NetHandlerPlayServer.func_73660_a(NetHandlerPlayServer.java:162)
[14:40:49] [Server thread/INFO] [STDERR]: [net.minecraftforge.lex.yunomakegoodmap.StructureUtil:loadTemplate:52]:       at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher$1.func_73660_a(NetworkDispatcher.java:213)
[14:40:49] [Server thread/INFO] [STDERR]: [net.minecraftforge.lex.yunomakegoodmap.StructureUtil:loadTemplate:52]:       at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:287)
[14:40:49] [Server thread/INFO] [STDERR]: [net.minecraftforge.lex.yunomakegoodmap.StructureUtil:loadTemplate:52]:       at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:180)
[14:40:49] [Server thread/INFO] [STDERR]: [net.minecraftforge.lex.yunomakegoodmap.StructureUtil:loadTemplate:52]:       at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:732)
[14:40:49] [Server thread/INFO] [STDERR]: [net.minecraftforge.lex.yunomakegoodmap.StructureUtil:loadTemplate:52]:       at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:387)
[14:40:49] [Server thread/INFO] [STDERR]: [net.minecraftforge.lex.yunomakegoodmap.StructureUtil:loadTemplate:52]:       at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:613)
[14:40:49] [Server thread/INFO] [STDERR]: [net.minecraftforge.lex.yunomakegoodmap.StructureUtil:loadTemplate:52]:       at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471)
[14:40:49] [Server thread/INFO] [STDERR]: [net.minecraftforge.lex.yunomakegoodmap.StructureUtil:loadTemplate:52]:       at java.lang.Thread.run(Thread.java:745)
[14:40:49] [Server thread/INFO] [STDERR]: [net.minecraftforge.lex.yunomakegoodmap.StructureUtil:loadTemplate:52]: java.io.FileNotFoundException: /home/fdw/home/AquaFactory-25885/config/YUNoMakeGoodMap/structures/SINGLE_GRASS_nether.nbt
[14:40:49] [Server thread/INFO] [STDERR]: [net.minecraftforge.lex.yunomakegoodmap.StructureUtil:loadTemplate:52]:       at net.minecraftforge.lex.yunomakegoodmap.StructureUtil.loadTemplate(StructureUtil.java:52)
[14:40:49] [Server thread/INFO] [STDERR]: [net.minecraftforge.lex.yunomakegoodmap.StructureUtil:loadTemplate:52]:       at net.minecraftforge.lex.yunomakegoodmap.generators.StructureLoader.generate(StructureLoader.java:36)
[14:40:49] [Server thread/INFO] [STDERR]: [net.minecraftforge.lex.yunomakegoodmap.StructureUtil:loadTemplate:52]:       at net.minecraftforge.lex.yunomakegoodmap.WorldProviderHellVoid$ChunkProviderHellVoid.func_185931_b(WorldProviderHellVoid.java:52)
[14:40:49] [Server thread/INFO] [STDERR]: [net.minecraftforge.lex.yunomakegoodmap.StructureUtil:loadTemplate:52]:       at org.spongepowered.mod.world.gen.SpongeChunkGeneratorForge.func_185931_b(SpongeChunkGeneratorForge.java:246)
[14:40:49] [Server thread/INFO] [STDERR]: [net.minecraftforge.lex.yunomakegoodmap.StructureUtil:loadTemplate:52]:       at net.minecraft.world.chunk.Chunk.func_186034_a(Chunk.java:1000)
[14:40:49] [Server thread/INFO] [STDERR]: [net.minecraftforge.lex.yunomakegoodmap.StructureUtil:loadTemplate:52]:       at net.minecraft.world.chunk.Chunk.func_186030_a(Chunk.java:983)
[14:40:49] [Server thread/INFO] [STDERR]: [net.minecraftforge.lex.yunomakegoodmap.StructureUtil:loadTemplate:52]:       at net.minecraft.world.gen.ChunkProviderServer.func_186025_d(ChunkProviderServer.java:154)
[14:40:49] [Server thread/INFO] [STDERR]: [net.minecraftforge.lex.yunomakegoodmap.StructureUtil:loadTemplate:52]:       at net.minecraft.world.World.func_72964_e(World.java:303)
[14:40:49] [Server thread/INFO] [STDERR]: [net.minecraftforge.lex.yunomakegoodmap.StructureUtil:loadTemplate:52]:       at net.minecraft.world.World.func_175726_f(World.java:298)
[14:40:49] [Server thread/INFO] [STDERR]: [net.minecraftforge.lex.yunomakegoodmap.StructureUtil:loadTemplate:52]:       at net.minecraft.world.World.func_180495_p(World.java:7003)
[14:40:49] [Server thread/INFO] [STDERR]: [net.minecraftforge.lex.yunomakegoodmap.StructureUtil:loadTemplate:52]:       at net.minecraft.world.Teleporter.findPortal(SourceFile:706)
[14:40:49] [Server thread/INFO] [STDERR]: [net.minecraftforge.lex.yunomakegoodmap.StructureUtil:loadTemplate:52]:       at net.minecraft.world.Teleporter.func_180620_b(SourceFile:669)
[14:40:49] [Server thread/INFO] [STDERR]: [net.minecraftforge.lex.yunomakegoodmap.StructureUtil:loadTemplate:52]:       at net.minecraft.world.Teleporter.func_180266_a(SourceFile:608)
[14:40:49] [Server thread/INFO] [STDERR]: [net.minecraftforge.lex.yunomakegoodmap.StructureUtil:loadTemplate:52]:       at org.spongepowered.common.entity.EntityUtil.handleDisplaceEntityPortalEvent(EntityUtil.java:417)
[14:40:49] [Server thread/INFO] [STDERR]: [net.minecraftforge.lex.yunomakegoodmap.StructureUtil:loadTemplate:52]:       at net.minecraft.server.management.PlayerList.transferPlayerToDimension(PlayerList.java:1822)
[14:40:49] [Server thread/INFO] [STDERR]: [net.minecraftforge.lex.yunomakegoodmap.StructureUtil:loadTemplate:52]:       at org.spongepowered.common.entity.EntityUtil.teleportPlayerToDimension(EntityUtil.java:250)
[14:40:49] [Server thread/INFO] [STDERR]: [net.minecraftforge.lex.yunomakegoodmap.StructureUtil:loadTemplate:52]:       at net.minecraft.entity.player.EntityPlayerMP.func_184204_a(EntityPlayerMP.java:4146)
[14:40:49] [Server thread/INFO] [STDERR]: [net.minecraftforge.lex.yunomakegoodmap.StructureUtil:loadTemplate:52]:       at net.minecraft.entity.Entity.func_70030_z(Entity.java:412)
[14:40:49] [Server thread/INFO] [STDERR]: [net.minecraftforge.lex.yunomakegoodmap.StructureUtil:loadTemplate:52]:       at net.minecraft.entity.EntityLivingBase.func_70030_z(EntityLivingBase.java:216)
[14:40:49] [Server thread/INFO] [STDERR]: [net.minecraftforge.lex.yunomakegoodmap.StructureUtil:loadTemplate:52]:       at net.minecraft.entity.Entity.func_70071_h_(Entity.java:359)
[14:40:49] [Server thread/INFO] [STDERR]: [net.minecraftforge.lex.yunomakegoodmap.StructureUtil:loadTemplate:52]:       at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:1932)
[14:40:49] [Server thread/INFO] [STDERR]: [net.minecraftforge.lex.yunomakegoodmap.StructureUtil:loadTemplate:52]:       at net.minecraft.entity.player.EntityPlayer.func_70071_h_(EntityPlayer.java:233)
[14:40:49] [Server thread/INFO] [STDERR]: [net.minecraftforge.lex.yunomakegoodmap.StructureUtil:loadTemplate:52]:       at net.minecraft.entity.player.EntityPlayerMP.func_71127_g(EntityPlayerMP.java:303)
[14:40:49] [Server thread/INFO] [STDERR]: [net.minecraftforge.lex.yunomakegoodmap.StructureUtil:loadTemplate:52]:       at net.minecraft.network.NetHandlerPlayServer.redirect$onPlayerTick$zhb000(NetHandlerPlayServer.java:1968)
[14:40:49] [Server thread/INFO] [STDERR]: [net.minecraftforge.lex.yunomakegoodmap.StructureUtil:loadTemplate:52]:       at net.minecraft.network.NetHandlerPlayServer.func_73660_a(NetHandlerPlayServer.java:162)
[14:40:49] [Server thread/INFO] [STDERR]: [net.minecraftforge.lex.yunomakegoodmap.StructureUtil:loadTemplate:52]:       at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher$1.func_73660_a(NetworkDispatcher.java:213)
[14:40:49] [Server thread/INFO] [STDERR]: [net.minecraftforge.lex.yunomakegoodmap.StructureUtil:loadTemplate:52]:       at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:287)
[14:40:49] [Server thread/INFO] [STDERR]: [net.minecraftforge.lex.yunomakegoodmap.StructureUtil:loadTemplate:52]:       at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:180)
[14:40:49] [Server thread/INFO] [STDERR]: [net.minecraftforge.lex.yunomakegoodmap.StructureUtil:loadTemplate:52]:       at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:732)
[14:40:49] [Server thread/INFO] [STDERR]: [net.minecraftforge.lex.yunomakegoodmap.StructureUtil:loadTemplate:52]:       at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:387)
[14:40:49] [Server thread/INFO] [STDERR]: [net.minecraftforge.lex.yunomakegoodmap.StructureUtil:loadTemplate:52]:       at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:613)
[14:40:49] [Server thread/INFO] [STDERR]: [net.minecraftforge.lex.yunomakegoodmap.StructureUtil:loadTemplate:52]:       at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471)
[14:40:49] [Server thread/INFO] [STDERR]: [net.minecraftforge.lex.yunomakegoodmap.StructureUtil:loadTemplate:52]:       at java.lang.Thread.run(Thread.java:745)

**Comment by LexManos** [comment]
Do those files exist? Also try without sponge.

**Comment by mkrtes** [comment]
Folder "structures" on the server is empty. I manually moved the files from .jar, but  .jar does not have _nether.nbt & SINGLE_GRASS_nether.nbt
It's SkyFactory 3 (3.0.6) mod-pack
Without Sponge all work correct.
